name: Plugin Code Generation Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        bun install
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Run Plugin Code Generation Tests
      run: bun test packages/scripts/tests/plugin-codegen.test.ts
      
    - name: Store generated plugins as artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: generated-plugins
        path: packages/plugins/
        if-no-files-found: ignore
